/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/": `/`,
  "/account": `/account`,
  "/appointments": `/appointments`,
  "/appointments/[appointmentId]": (params: { appointmentId: (string | number) }) => {
    return `/appointments/${params['appointmentId']}`
  },
  "/documents": `/documents`,
  "/documents/[documentId]": (params: { documentId: (string | number) }) => {
    return `/documents/${params['documentId']}`
  },
  "/labs": `/labs`,
  "/labs/[coding]": (params: { coding: (string | number) }) => {
    return `/labs/${params['coding']}`
  },
  "/module/oncology": `/module/oncology`,
  "/tasks": `/tasks`,
  "/tasks/[id]": (params: { id: (string | number) }) => {
    return `/tasks/${params['id']}`
  },
  "/login": `/login`,
  "/login/callback": `/login/callback`
}

/**
 * SERVERS
 */
const SERVERS = {
  "GET /fhir/resolveReference": `/fhir/resolveReference`,
  "GET /documents/[documentId]": (params: { documentId: (string | number) }) => {
    return `/documents/${params['documentId']}`
  }
}

/**
 * ACTIONS
 */
const ACTIONS = {
  "logoutEverywhere /account": `/account?/logoutEverywhere`,
  "uploadDocument /documents": `/documents?/uploadDocument`,
  "login /login": `/login?/login`,
  "login /login/callback": `/login/callback?/login`
}

/**
 * LINKS
 */
const LINKS = {
  
}

type ParamValue = string | number | undefined

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?',
) => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  let anchor = ''
  for (const [name, val] of Object.entries(sp)) {
    if (name === '__KIT_ROUTES_ANCHOR__' && val !== undefined) {
      anchor = `#${val}`
      continue
    }
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted || anchor) {
    return `${prefix}${formatted}${anchor}`.replace('?#', '#')
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

// route function helpers
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

export type Routes = keyof AllTypes extends `${string}/${infer Route}` ? `/${Route}` : keyof AllTypes
export const routes = [
	...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[]

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/': never, '/account': never, '/appointments': never, '/appointments/[appointmentId]': 'appointmentId', '/documents': never, '/documents/[documentId]': 'documentId', '/labs': never, '/labs/[coding]': 'coding', '/module/oncology': never, '/tasks': never, '/tasks/[id]': 'id', '/login': never, '/login/callback': never }
  SERVERS: { 'GET /fhir/resolveReference': never, 'GET /documents/[documentId]': 'documentId' }
  ACTIONS: { 'logoutEverywhere /account': never, 'uploadDocument /documents': never, 'login /login': never, 'login /login/callback': never }
  LINKS: Record<string, never>
  Params: { 'appointmentId': never, 'documentId': never, 'coding': never, 'id': never }
}
