services:
  mockoon:
    image: mockoon/cli:latest
    command: --data "/data/mockoon-config.json" --port 3000
    volumes:
      - ./samples/mockoon.json:/data/mockoon-config.json:ro
      - ./samples/fhir:/data/fhir:ro
    ports:
      - 3000:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  # oidc-mock:
  #   build:
  #     context: ./samples/oidc-mock-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
  #   healthcheck:
  #     test: wget --spider --server-response --quiet "http://127.0.0.1:8080/.well-known/openid-configuration" 2>&1 | grep -q "200 OK"
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "local"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      mockoon:
        condition: service_healthy
      # oidc-mock:
      #   condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - ORIGIN=http://localhost:5174
    env_file:
      - .env.mockoon.docker
    restart: unless-stopped
    ports:
      - 5174:3000
      - 8080:8080
